### ISSUE TITLE
Language specific code highlighting

### ISSUE THREAD

**Issue by letalvoj** [nicbou/markdown-notes#11]
Hi, 

nice app, love it! I have a minor issue with the code highlighting. It seems to me, that it ignores the specified language and for example the following snipped is displayed ugly:

> ```scala
>   val something = collection.reduce((u,v) => u+v).map("Result: "+ _)
> ```

and not at all like:

``` scala
    val something = collection.reduce((u,v) => u+v).map("Result: "+ _)
```

Can you confirm it please, or it is just me missing something?

**Comment by nicbou** [comment]
Yep, I noticed the same thing recently too. I'm marking it as a bug.
