### ISSUE TITLE
Share button

### ISSUE THREAD

**Issue by letalvoj** [nicbou/markdown-notes#12]
The thing which I miss the most from the app is a simple **share** button, which would give me a link to share with colleges. Not for editing, only the _preview_.

**Comment by nicbou** [comment]
That would be fairly easy to achieve and it's the second time someone requests it. Marking as enhancement.

**Comment by nicbou** [comment]
Note sharing is implemented and working on my local repo, but I still have to add the share button (easy peasy) and test everything.

**Comment by letalvoj** [comment]
Owesome. Looking rorward seeing it on the web 😉

**Comment by nicbou** [comment]
Finished with commit 2f9764c6b0ec8c8892

**Comment by nicbou** [comment]
This feature is already proving far more useful than expected. Thanks a lot for the suggestion, @letalvoj
