### ISSUE TITLE
Inline LaTeX is cloned in the line below

### ISSUE THREAD

**Issue by fvisin** [nicbou/markdown-notes#14]
The following example is not correctly parsed:
`For some reason this is parsed correctly $$$Z_{1..5}$$$ but this is not $$X_{1..5}$$`

The first LaTeX formula is as expected, but the output of the second one is repeated a second time in the line below resulting in something like this:

```
but this is not X1..5
                  X1..5
```

This is happening on Linux Ubuntu 14.04 kernel 3.17.0-031700-generic with Google Chrome 45.0.2454.85.

**Comment by fvisin** [comment]
A workaround is to use `$$X_{1\dots5}$$`

**Comment by nicbou** [comment]
I have just tried on my side, and it's coming out as it should on OSX with Chrome 45.0.2454.85. Could you post the full note along with a screenshot?

![screen shot 2015-09-08 at 10 26 54 am](https://cloud.githubusercontent.com/assets/88917/9730073/3a13f638-5614-11e5-855c-2e150c61721b.png)

**Comment by fvisin** [comment]
Here is it, thank you for the support.
![screenshot from 2015-09-08 22 58 49](https://cloud.githubusercontent.com/assets/4639261/9752379/65d499c6-567d-11e5-8b34-6dd2a240facf.png)

**Comment by nicbou** [comment]
Doesn't it display as it should? `$$$` creates block equations while `$$` creates inline equations.

**Comment by fvisin** [comment]
Ops....sorry, I created a snippet in a rush to just show the bug and I didn't notice there was no bug in there! 

Here is another screenshot [1] showing the bug:
![1](https://cloud.githubusercontent.com/assets/4639261/9780397/3115d40a-5756-11e5-9228-0b0ee0debb9d.png)

Apparently once the bug is triggered new LaTeX formulas are rendered incorrectly, e.g., after taking screenshot [1] I deleted all the text and pasted the sentence of the previous comment and it is rendered incorrectly:
![0](https://cloud.githubusercontent.com/assets/4639261/9780403/42855ea4-5756-11e5-911d-ecbd512d2586.png)

**Comment by fvisin** [comment]
Apparently I am not able to reproduce the bug. I think it is triggered when part of the text is modified or deleted, but I don't remember how I modified the note to get to the situation of the first screenshot. If I just copy and paste the same sentence now it is rendered correctly. I am puzzled. I will try to collect more information and come back if I find something.

**Comment by nicbou** [comment]
Any news on this bug? If it still can't be reproduced, I will close it

**Comment by fvisin** [comment]
I tried a couple of times without being able to reproduce it. I'd like to understand what triggers it, but I don't foresee to have time to check it properly in the near future so I will close the issue.
