### ISSUE TITLE
Multiple tabs open on the same note can cause data loss

### ISSUE THREAD

**Issue by TomHodson** [nicbou/markdown-notes#23]
Steps to reproduce:
1. open a tab on a given note
2. open another tab on the same note and make an edit
3. go to the first tab and make an edit

The first edit will be lost, this has bitten me a couple of times.

I'm not sure what the simplest way to fix this is, but I suggest the frontend keeps track of the last time it has has saved to the server, and before it does another save it checks that the file hasn't updated in the meantime.

Alternatively, make the frontend pull down the server's copy of the note before it ever modifies it.

**Comment by nicbou** [comment]
There is no easy way to handle this. Multi-user synchronization is a fairly complex problem to work with, and I would rather focus effort on more pressing issues such as offline usage.
