### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by AuHau** [nicbou/markdown-notes#33]
Hey there,

I would suggest to create API documentation for example with https://apiary.io/. I used it on one of my projects and it is quiet nice way how to document and also test API (example from my project: http://docs.icalian.apiary.io/ ).

I want to work on the #6 issue so I will try to make the documentation after I will be finished.

**Comment by nicbou** [comment]
The API is a simple REST API. Since it doesn't have any external user, I don't think it would be really useful

**Comment by AuHau** [comment]
Ok if you think so. 
Maybe it would be useful for people who would like to contribute, because at least so far I have not figured out how to easily find the routes for the API (you have to know how Tastypie works and how to derive the routes from the Resources name)...
