### ISSUE TITLE
Dragging and dropping images only works in Chrome

### ISSUE THREAD

**Issue by nicbou** [nicbou/markdown-notes#44]
As reported by a user, the dragging and dropping of images only works in Chrome. Firefox and Safari do not fire the event or show the cursor. Dropping the image simply loads the image in the tab.

**Comment by AuHau** [comment]
Fixed in Firefox. Not sure about Safari, since I am not running Mac OS. 
Please if somebody with Mac OS could check what is the issue on Safari, it would be highly appreciated.

**Comment by AuHau** [comment]
Safari fixed in #48. 
Now waiting for deploy.
